export const COLLABORATORS_SHEET_HEADERS = [
  'Rut',
  'Rut',
  'DV',
  'N°Ficha',
  'NombreCompleto',
  'Empresa',
  'Area',
  'Estado',
  'SubEstado',
  'FechaFinLicencia',
  'TipodeContrato',
  'JornadaLaboral',
  'Cliente',
  'Servicio',
  'Campaña',
  'Cargo',
  'Supervisor',
  'Coordinador',
  'SubGerente',
  'Genero',
  'FechaNacimiento',
  'EstadoCivil',
  'Nacionalidad',
  'CorreoPersonal',
  'TelefonoCelular',
  'TelefonoFijo',
  'Direccion',
  'Comuna',
  'Ciudad',
  'NivelEducacional',
  'Especialidad',
  'ContactoEmergencia',
  'ParentescoEmergencia',
  'TelefonoEmergencia',
  'Alergias',
  'FechaAlta',
  'FechaBaja',
  'Antigüedad  (dias)',
  'MotivoBaja',
  'TipoRemuneracion',
  'IDCentroCosto',
  'DescripcionCentroCosto',
  'Rol',
  'BancoTransferencia',
  'TipodeCuentaTransferencia',
  'N°deCuenta',
  'Cargasfamiliares',
  'Salud',
  'AFP',
  'FechaContrato',
  'TerminoContrato',
  'RegistroContratoDT',
  '1° RenovacionContrato',
  '1° TerminoRenovacionContrato',
  'RenovacionContratoIndefido',
  'SueldoBruto',
  'Gratificacion',
  'Movilizacion',
  'Colacion',
  'Anexo confidencialidad',
  'Anexo horario',
  'Anexo cambio renta',
  'Pacto HHEE',
  'Sindicato',
  'Demanda',
  'Notebook',
  'Llaves Oficina Cerr.Superior',
  'Llaves Oficina Cerr.Inferior',
  'Correocoorporativo',
  'CorreoGmailcoorporativo',
  'Correocliente',
] as const;

export type CollaboratorsSheetHeader = (typeof COLLABORATORS_SHEET_HEADERS)[number];

